from django.core.management.base import BaseCommand
from core.models import Cafe, Spot

CAFES = [
    {
        'name': 'Prufrock Coffee',
        'address': '23-25 Leather Ln',
        'city': 'London',
        'latitude': 51.5204,
        'longitude': -0.1086,
        'has_power_outlets': True,
        'wifi_speed_mbps': 85,
        'quiet_rating': 3,
    },
    {
        'name': 'Grind Shoreditch',
        'address': '85-86 Old St',
        'city': 'London',
        'latitude': 51.5256,
        'longitude': -0.0877,
        'has_power_outlets': True,
        'wifi_speed_mbps': 100,
        'quiet_rating': 2,
    },
    {
        'name': 'The Watch House',
        'address': '199 Bermondsey St',
        'city': 'London',
        'latitude': 51.5002,
        'longitude': -0.0815,
        'has_power_outlets': False,
        'wifi_speed_mbps': 50,
        'quiet_rating': 4,
    },
    {
        'name': 'Foundation Coffee House',
        'address': '25 Lever St',
        'city': 'Manchester',
        'latitude': 53.4832,
        'longitude': -2.2331,
        'has_power_outlets': True,
        'wifi_speed_mbps': 120,
        'quiet_rating': 5,
    },
    {
        'name': 'Takk Coffee Co.',
        'address': '6 Tariff St',
        'city': 'Manchester',
        'latitude': 53.4818,
        'longitude': -2.2312,
        'has_power_outlets': True,
        'wifi_speed_mbps': 90,
        'quiet_rating': 4,
    },
    {
        'name': 'Ezra & Gil',
        'address': '20 Hilton St',
        'city': 'Manchester',
        'latitude': 53.4827,
        'longitude': -2.2325,
        'has_power_outlets': True,
        'wifi_speed_mbps': 75,
        'quiet_rating': 3,
    },
    {
        'name': 'Strangers Coffee House',
        'address': '21 Wensum St',
        'city': 'Norwich',
        'latitude': 52.6321,
        'longitude': 1.2965,
        'has_power_outlets': True,
        'wifi_speed_mbps': 65,
        'quiet_rating': 3,
    },
    {
        'name': 'The Birdcage',
        'address': '23 Pottergate',
        'city': 'Norwich',
        'latitude': 52.6304,
        'longitude': 1.2937,
        'has_power_outlets': False,
        'wifi_speed_mbps': 40,
        'quiet_rating': 4,
    },
    {
        'name': 'Costa Coffee (Belvaros)',
        'address': '1 Regent Rd',
        'city': 'Great Yarmouth',
        'latitude': 52.6076,
        'longitude': 1.7305,
        'has_power_outlets': True,
        'wifi_speed_mbps': 55,
        'quiet_rating': 3,
        'members_only': False,
    },
    {
        'name': 'Starbucks Coffee (Market Gates)',
        'address': '31 Market Gates',
        'city': 'Great Yarmouth',
        'latitude': 52.6067,
        'longitude': 1.7280,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 2,
        'members_only': True,
    },
    {
        'name': 'The Vault',
        'address': '156 High St',
        'city': 'Gorleston-on-Sea',
        'latitude': 52.5763,
        'longitude': 1.7256,
        'has_power_outlets': False,
        'wifi_speed_mbps': 45,
        'quiet_rating': 4,
        'members_only': True,
    },
    {
        'name': 'Starbucks Coffee (Gapton Hall)',
        'address': 'Gapton Hall Rd',
        'city': 'Great Yarmouth',
        'latitude': 52.5930,
        'longitude': 1.7057,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 2,
        'members_only': True,
    },
    {
        'name': 'Strangers Coffee Company',
        'address': '21 Pottergate',
        'city': 'Norwich',
        'latitude': 52.6299,
        'longitude': 1.2900,
        'has_power_outlets': True,
        'wifi_speed_mbps': 70,
        'quiet_rating': 3,
        'members_only': False,
    },
    {
        'name': 'Costa Coffee (Norwich Station)',
        'address': 'Station Approach',
        'city': 'Norwich',
        'latitude': 52.6266,
        'longitude': 1.3080,
        'has_power_outlets': True,
        'wifi_speed_mbps': 55,
        'quiet_rating': 2,
        'members_only': True,
    },
    {
        'name': 'Costa Coffee (Manchester Piccadilly Station)',
        'address': 'Piccadilly Station, Unit 1',
        'city': 'Manchester',
        'latitude': 53.4773,
        'longitude': -2.2309,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 2,
        'members_only': False,
    },
    {
        'name': 'Costa Coffee (Cranbrook Road)',
        'address': '24 Cranbrook Rd',
        'city': 'Ilford',
        'latitude': 51.5590,
        'longitude': 0.0741,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 3,
        'members_only': True,
    },
    {
        'name': 'Costa Coffee (The Exchange Shopping Centre)',
        'address': 'High Rd',
        'city': 'Ilford',
        'latitude': 51.5578,
        'longitude': 0.0691,
        'has_power_outlets': True,
        'wifi_speed_mbps': 45,
        'quiet_rating': 3,
        'members_only': True,
    },
    {
        'name': 'Costa Coffee (The Albion Centre)',
        'address': 'Unit 2A, The Albion Centre',
        'city': 'Ilkeston',
        'latitude': 52.9706,
        'longitude': -1.3080,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 3,
        'members_only': True,
    },
    {
        'name': 'The Ilkeston Coffee Bean',
        'address': '154 Bath St',
        'city': 'Ilkeston',
        'latitude': 52.9688,
        'longitude': -1.3050,
        'has_power_outlets': True,
        'wifi_speed_mbps': 45,
        'quiet_rating': 4,
        'members_only': True,
    },
    {
        'name': 'Costa Coffee (Gorleston High Street)',
        'address': '134-136 High St',
        'city': 'Gorleston-on-Sea',
        'latitude': 52.5766,
        'longitude': 1.7260,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 3,
        'members_only': True,
    },
    {
        'name': 'Unthank Kitchen',
        'address': '117 Unthank Rd',
        'city': 'Norwich',
        'latitude': 52.6236,
        'longitude': 1.2789,
        'has_power_outlets': True,
        'wifi_speed_mbps': 60,
        'quiet_rating': 4,
        'members_only': False,
    },
    {
        'name': 'Kofra Speciality Coffee',
        'address': '16 Onley St',
        'city': 'Norwich',
        'latitude': 52.6280,
        'longitude': 1.2870,
        'has_power_outlets': True,
        'wifi_speed_mbps': 60,
        'quiet_rating': 5,
        'members_only': True,
    },
    {
        'name': 'Grind & Go',
        'address': '113 Cranbrook Rd',
        'city': 'Ilford',
        'latitude': 51.5595,
        'longitude': 0.0745,
        'has_power_outlets': True,
        'wifi_speed_mbps': 45,
        'quiet_rating': 4,
        'members_only': True,
    },
    {
        'name': 'Perky Blenders',
        'address': '66 High St',
        'city': 'Wanstead',
        'latitude': 51.5760,
        'longitude': 0.0287,
        'has_power_outlets': True,
        'wifi_speed_mbps': 55,
        'quiet_rating': 3,
        'members_only': True,
    },
    {
        'name': '200 Degrees Coffee Shop',
        'address': '16 Flying Horse Walk',
        'city': 'Nottingham',
        'latitude': 52.9540,
        'longitude': -1.1500,
        'has_power_outlets': True,
        'wifi_speed_mbps': 55,
        'quiet_rating': 3,
        'members_only': False,
    },
    {
        'name': 'The Clean Cut Kitchen',
        'address': '11 Derby Rd',
        'city': 'Derby',
        'latitude': 52.9225,
        'longitude': -1.4746,
        'has_power_outlets': True,
        'wifi_speed_mbps': 50,
        'quiet_rating': 3,
        'members_only': True,
    },
]


class Command(BaseCommand):
    help = 'Adds the starter list of cafes to the databse'

    def handle(self, *args, **kwargs):
        for cafe_data in CAFES:
            cafe, created = Cafe.objects.get_or_create(
                name=cafe_data['name'],
                defaults=cafe_data,
            )
            if created:
                Spot.objects.create(cafe=cafe, spot_name='Main area', capacity=4)
                self.stdout.write('Added ' + cafe.name)
            else:
                self.stdout.write(cafe.name + ' alredy exists')
