# Generated by Django 6.1.1 on 2026-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cafe_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
