# Generated by Django 6.1.1 on 2026-09-16 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cafe_latitude_alter_cafe_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favourite_cafes', to=settings.AUTH_USER_MODEL),
        ),
    ]
