# Generated by Django 6.1.1 on 2026-09-24 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cafe_favourited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
